---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
  name: {{ .Values.ingress.rest.name }}
spec:
  rules:
  - host: {{ .Values.ingress.rest.host }}
    http:
      paths:
      - backend:
          serviceName: {{ template "fullname" . }}
          servicePort: {{ .Values.service.port | int }}
        path: /
  tls:
  - hosts:
    - {{ .Values.ingress.rest.host }}
    secretName: {{ .Values.name }}-tls
---
